/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import capaNegocio.cls_Trabajador;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class Frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Frm_PRec
     */
    public Frm_Principal() {
        initComponents();
        getIconImage();
    }

    private boolean validarAcceso(String cargosConPermiso) {
        Jd_IniciarSesion objIS = new Jd_IniciarSesion(this, true);
        String cargoSesionActual = objIS.cargo.substring(0, 1).toLowerCase();
        if (cargosConPermiso.contains(cargoSesionActual)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "No tienes permiso para acceder a este formulario", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    @Override
    public Image getIconImage() {
        Image valorRetorno = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("media/logo-simbolo-aurora-dental.png"));
        return valorRetorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblnombreCargo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        CerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        mnuReporte1 = new javax.swing.JMenuItem();
        mnuReporte2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        mnuReporte3Errea = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        mnuReporte05Saavedra = new javax.swing.JMenuItem();
        mnuReporte6Errea = new javax.swing.JMenuItem();
        mnuReporte7Errea = new javax.swing.JMenuItem();
        mnuReporte8Saavedra = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        mnuReporte9Espinoza = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        mnuReporte14Juan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo-completo-aurora-dental-small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel3)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(138, 241, 248));

        lblnombreCargo.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblnombreCargo.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 124, 155));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnombreCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombreCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Perfil");
        jMenu1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/address-card-solid.png"))); // NOI18N
        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/right-from-bracket-solid.png"))); // NOI18N
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(CerrarSesion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pacientes");
        jMenu2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/user-plus-solid.png"))); // NOI18N
        jMenu3.setText("Registrar");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/user-plus-solid.png"))); // NOI18N
        jMenuItem2.setText("Nueva persona");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/tooth-solid.png"))); // NOI18N
        jMenuItem3.setText("Desde trabajador");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu2.add(jMenu3);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/user-pen-solid.png"))); // NOI18N
        jMenuItem9.setText("Actualizar información");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/clipboard-list-solid.png"))); // NOI18N
        jMenuItem4.setText("Atenciones Pendientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Citas");
        jMenu5.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/calendar-plus-solid.png"))); // NOI18N
        jMenuItem5.setText("Agendar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/calendar-days-solid.png"))); // NOI18N
        jMenuItem6.setText("Modificar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);
        jMenu5.add(jSeparator1);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/user-tie-solid.png"))); // NOI18N
        jMenuItem8.setText("Por paciente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/tooth-solid.png"))); // NOI18N
        jMenuItem10.setText("Por odontólogo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Pagos");
        jMenu8.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/receipt-solid.png"))); // NOI18N
        jMenuItem21.setText("Registrar pago");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem21);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/file-invoice-solid.png"))); // NOI18N
        jMenuItem22.setText("Consultar por paciente");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuBar1.add(jMenu8);

        jMenu4.setText("Gestión");
        jMenu4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/user-tie-solid.png"))); // NOI18N
        jMenuItem18.setText("Recepcionistas");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/tooth-solid.png"))); // NOI18N
        jMenuItem19.setText("Odontológos");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem19);
        jMenu4.add(jSeparator4);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/color1/clipboard-list-solid.png"))); // NOI18N
        jMenuItem20.setText("Tratamientos");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jMenu7.setText("Reportes financieros");

        mnuReporte1.setText("Ganacias por mes y semana");
        mnuReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte1ActionPerformed(evt);
            }
        });
        jMenu7.add(mnuReporte1);

        mnuReporte2.setText("Tratamientos con mas ingresos");
        mnuReporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte2ActionPerformed(evt);
            }
        });
        jMenu7.add(mnuReporte2);

        jMenu6.add(jMenu7);

        jMenu9.setText("Reportes sobre recepcionistas");

        mnuReporte3Errea.setText("Cantidad de citas agendadas por semanas");
        mnuReporte3Errea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte3ErreaActionPerformed(evt);
            }
        });
        jMenu9.add(mnuReporte3Errea);

        jMenu6.add(jMenu9);

        jMenu10.setText("Reportes sobre odontologos");

        mnuReporte05Saavedra.setText("Rendimiento por tiempo");
        mnuReporte05Saavedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte05SaavedraActionPerformed(evt);
            }
        });
        jMenu10.add(mnuReporte05Saavedra);

        mnuReporte6Errea.setText("Horas de trabajo");
        mnuReporte6Errea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte6ErreaActionPerformed(evt);
            }
        });
        jMenu10.add(mnuReporte6Errea);

        mnuReporte7Errea.setText("Modificaciones de actos médicos");
        mnuReporte7Errea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte7ErreaActionPerformed(evt);
            }
        });
        jMenu10.add(mnuReporte7Errea);

        mnuReporte8Saavedra.setText("Con más citas agendadas");
        mnuReporte8Saavedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte8SaavedraActionPerformed(evt);
            }
        });
        jMenu10.add(mnuReporte8Saavedra);

        jMenu6.add(jMenu10);

        jMenu11.setText("Reportes sobre pacientes");

        mnuReporte9Espinoza.setText("Frecuencia por edad");
        mnuReporte9Espinoza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte9EspinozaActionPerformed(evt);
            }
        });
        jMenu11.add(mnuReporte9Espinoza);

        jMenu6.add(jMenu11);

        jMenu12.setText("Reporte sobre tratamientos");

        mnuReporte14Juan.setText("Ingresos por tratamientos");
        mnuReporte14Juan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporte14JuanActionPerformed(evt);
            }
        });
        jMenu12.add(mnuReporte14Juan);

        jMenu6.add(jMenu12);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (validarAcceso("r")) {
            Jd_ActualizarPA objdAP = new Jd_ActualizarPA(this, true);
            objdAP.setLocationRelativeTo(this);
            objdAP.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (validarAcceso("r")) {
            Jd_ProgramarCita objd_ProCita = new Jd_ProgramarCita(this, true);
            objd_ProCita.setLocationRelativeTo(this);
            objd_ProCita.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (validarAcceso("r")) {
            Jd_ReagendarCita objdMC = new Jd_ReagendarCita(this, true);
            objdMC.setLocationRelativeTo(this);
            objdMC.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (validarAcceso("r")) {
            Jd_ConsultarCita_Paciente objdCCP = new Jd_ConsultarCita_Paciente(this, true);
            objdCCP.setLocationRelativeTo(this);
            objdCCP.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if (validarAcceso("r")) {
            Jd_ConsultarCita_Doctor objdCCD = new Jd_ConsultarCita_Doctor(this, true);
            objdCCD.setLocationRelativeTo(this);
            objdCCD.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (validarAcceso("gro")) {
            Jd_EditarPerfil objdUsu = new Jd_EditarPerfil(this, true);
            objdUsu.setLocationRelativeTo(this);
            objdUsu.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        if (validarAcceso("gro")) {
            Jd_IniciarSesion objIS = new Jd_IniciarSesion(this, true);
            objIS.nombreCompleto = "";
            objIS.cargo = "";
            objIS.username = "";
            objIS.id_usuario = 0;
            lblnombreCargo.setText("");
            jLabel1.setText("");
            objIS.setLocationRelativeTo(this);
            objIS.setVisible(true);
            jLabel1.setText("Usuario:");
            lblnombreCargo.setText(Jd_IniciarSesion.nombreCompleto + " - " + Jd_IniciarSesion.cargo);
        }
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (validarAcceso("r")) {
            Jd_RegistrarPa objdRP = new Jd_RegistrarPa(this, true);
            objdRP.setLocationRelativeTo(this);
            objdRP.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (validarAcceso("r")) {
            Jd_RegistrarPa_Doctor objRPD = new Jd_RegistrarPa_Doctor(this, true);
            objRPD.setLocationRelativeTo(this);
            objRPD.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (validarAcceso("o")) {
            Jd_AtencionPacientesPendientes objdAPP;
            try {
                objdAPP = new Jd_AtencionPacientesPendientes(this, true);
                objdAPP.setLocationRelativeTo(this);
                objdAPP.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (validarAcceso("r")) {
            FrmAppPlantillas objF = new FrmAppPlantillas();
            objF.setLocationRelativeTo(this);
            objF.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Jd_IniciarSesion objIS = new Jd_IniciarSesion(this, true);
        objIS.setLocationRelativeTo(this);
        objIS.setVisible(true);
        jLabel1.setText("Usuario:");
        lblnombreCargo.setText(Jd_IniciarSesion.nombreCompleto + " - " + Jd_IniciarSesion.cargo);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        if (validarAcceso("g")) {
            Jd_Gestion_Tratamiento objGT = new Jd_Gestion_Tratamiento(this, true);
            objGT.setLocationRelativeTo(this);
            objGT.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        if (validarAcceso("r")) {
            Jd_RegistrarPago objP = new Jd_RegistrarPago(this, true);
            objP.setLocationRelativeTo(this);
            objP.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        if (validarAcceso("gr")) {
            Jd_Consultar_Pagos_Paciente objCPP = new Jd_Consultar_Pagos_Paciente(this, true);
            objCPP.setLocationRelativeTo(this);
            objCPP.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        if (validarAcceso("g")) {
            Jd_Gestion_Odontologo objGO = new Jd_Gestion_Odontologo(this, true);
            objGO.setLocationRelativeTo(this);
            objGO.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        if (validarAcceso("g")) {
            Jd_Gestion_Recepcionista objGR = new Jd_Gestion_Recepcionista(this, true);
            objGR.setLocationRelativeTo(this);
            objGR.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void mnuReporte05SaavedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte05SaavedraActionPerformed
        // TODO add your handling code here:
        jdReporte05Saavedra objR5Saavedra = new jdReporte05Saavedra(this, true);
        objR5Saavedra.setLocationRelativeTo(this);
        objR5Saavedra.setVisible(true);
    }//GEN-LAST:event_mnuReporte05SaavedraActionPerformed

    private void mnuReporte6ErreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte6ErreaActionPerformed
        // TODO add your handling code here:
        jdReporte06Saavedra objR6Saavedra = new jdReporte06Saavedra(this, true);
        objR6Saavedra.setLocationRelativeTo(this);
        objR6Saavedra.setVisible(true);
    }//GEN-LAST:event_mnuReporte6ErreaActionPerformed

    private void mnuReporte8SaavedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte8SaavedraActionPerformed
        // TODO add your handling code here:
        jdReporte08Saavedra objR8Saavedra = new jdReporte08Saavedra(this, true);
        objR8Saavedra.setLocationRelativeTo(this);
        objR8Saavedra.setVisible(true);
    }//GEN-LAST:event_mnuReporte8SaavedraActionPerformed

    private void mnuReporte3ErreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte3ErreaActionPerformed
        // TODO add your handling code here:
        jdReporte03Errea objR3Errea = new jdReporte03Errea(this, true);
        objR3Errea.setLocationRelativeTo(this);
        objR3Errea.setVisible(true);
    }//GEN-LAST:event_mnuReporte3ErreaActionPerformed

    private void mnuReporte7ErreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte7ErreaActionPerformed
        // TODO add your handling code here:
        jdReporte07Errea objR7Errea = new jdReporte07Errea(this, true);
        objR7Errea.setLocationRelativeTo(this);
        objR7Errea.setVisible(true);
    }//GEN-LAST:event_mnuReporte7ErreaActionPerformed

    private void mnuReporte9EspinozaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte9EspinozaActionPerformed
        // TODO add your handling code here:
        jdReporte09Espinoza objR9Juan = new jdReporte09Espinoza(this, true);
        objR9Juan.setLocationRelativeTo(this);
        objR9Juan.setVisible(true);
    }//GEN-LAST:event_mnuReporte9EspinozaActionPerformed

    private void mnuReporte14JuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte14JuanActionPerformed
        // TODO add your handling code here:
        jdReporte14Espinoza objR14Juan = new jdReporte14Espinoza(this, true);
        objR14Juan.setLocationRelativeTo(this);
        objR14Juan.setVisible(true);
    }//GEN-LAST:event_mnuReporte14JuanActionPerformed

    private void mnuReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte1ActionPerformed
        jdReporte01Barboza objR1Luis = new jdReporte01Barboza(this, true);
        objR1Luis.setLocationRelativeTo(this);
        objR1Luis.setVisible(true);
    }//GEN-LAST:event_mnuReporte1ActionPerformed

    private void mnuReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporte2ActionPerformed
        jdReporte02Barboza objR2Luis = new jdReporte02Barboza(this, true);
        objR2Luis.setLocationRelativeTo(this);
        objR2Luis.setVisible(true);
    }//GEN-LAST:event_mnuReporte2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblnombreCargo;
    private javax.swing.JMenuItem mnuReporte05Saavedra;
    private javax.swing.JMenuItem mnuReporte1;
    private javax.swing.JMenuItem mnuReporte14Juan;
    private javax.swing.JMenuItem mnuReporte2;
    private javax.swing.JMenuItem mnuReporte3Errea;
    private javax.swing.JMenuItem mnuReporte6Errea;
    private javax.swing.JMenuItem mnuReporte7Errea;
    private javax.swing.JMenuItem mnuReporte8Saavedra;
    private javax.swing.JMenuItem mnuReporte9Espinoza;
    // End of variables declaration//GEN-END:variables
}
